"""
diagnose_embeddings_v2.py
=========================
Checks whether train (2001-2023) and test (2024-2026) embeddings
are comparable — same model, same scale, same distribution.

If they were generated by different BERT models or preprocessing,
cosine similarity will be artificially low even for identical text.

Usage
-----
    python diagnose_embeddings_v2.py \
        --train "memory_2001_2023/price_event_memory.json" \
        --test  "memory_2024_2026/df_major_memory_2024_2026.jsonl"
"""

import argparse, json, re, sys
import numpy as np
from pathlib import Path
from sklearn.preprocessing import normalize

def strip_ansi(s):
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", " ", s)

def parse_emb(raw):
    if raw is None: return None
    if isinstance(raw, (list, np.ndarray)):
        return np.array(raw, dtype=np.float32).ravel()
    if isinstance(raw, str):
        clean = strip_ansi(raw).replace("[","").replace("]","").replace("\n"," ")
        nums = []
        for t in clean.split():
            try: nums.append(float(t.rstrip(",")))
            except: pass
        if len(nums) >= 100:
            return np.array(nums, dtype=np.float32)
    return None

def load_sample(path: Path, n=50):
    """Load first n valid embeddings from a JSON or JSONL file."""
    embs, texts = [], []
    path = Path(path)

    with path.open("r", encoding="utf-8", errors="replace") as f:
        first = ""
        for line in f:
            first = line.strip()
            if first: break

    if first.startswith("["):
        with path.open("r", encoding="utf-8", errors="replace") as f:
            data = json.load(f)
        rows = data[:n*2]
    else:
        rows = []
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line: continue
                try: rows.append(json.loads(line))
                except: pass
                if len(rows) >= n*2: break

    for row in rows:
        e = parse_emb(row.get("bert_embeddings"))
        if e is not None and len(e) >= 100:
            if len(e) < 768: e = np.pad(e, (0, 768-len(e)))
            else: e = e[:768]
            embs.append(e)
            texts.append(str(row.get("text",""))[:80])
        if len(embs) >= n:
            break

    return np.stack(embs), texts

def stats(X, label):
    print(f"\n{'─'*55}")
    print(f"  {label}")
    print(f"{'─'*55}")
    print(f"  shape         : {X.shape}")
    print(f"  mean          : {X.mean():.6f}  (should be ~0 for BERT)")
    print(f"  std           : {X.std():.6f}")
    print(f"  min / max     : {X.min():.4f} / {X.max():.4f}")
    norms = np.linalg.norm(X, axis=1)
    print(f"  L2 norm mean  : {norms.mean():.4f}  std={norms.std():.4f}")
    print(f"  L2 norm range : [{norms.min():.4f}, {norms.max():.4f}]")
    # Check for zero vectors
    zero = (norms < 0.01).sum()
    print(f"  zero vectors  : {zero}")
    # Check for NaN/Inf
    bad = (~np.isfinite(X)).sum()
    print(f"  NaN/Inf values: {bad}")
    # First 5 values of first embedding
    print(f"  first emb[0:5]: {X[0,:5].round(4)}")

def cosine_sim_matrix(A, B):
    An = normalize(A, norm="l2")
    Bn = normalize(B, norm="l2")
    return An @ Bn.T

ap = argparse.ArgumentParser()
ap.add_argument("--train", required=True)
ap.add_argument("--test",  required=True)
ap.add_argument("--n",     type=int, default=50)
args = ap.parse_args()

print("="*55)
print("EMBEDDING COMPATIBILITY DIAGNOSTIC")
print("="*55)

print(f"\n[load] train: {Path(args.train).name}")
X_train, train_texts = load_sample(args.train, args.n)
print(f"  loaded {len(X_train)} embeddings")

print(f"\n[load] test: {Path(args.test).name}")
X_test, test_texts = load_sample(args.test, args.n)
print(f"  loaded {len(X_test)} embeddings")

# ── Per-corpus statistics ──────────────────────────────────────────────────────
stats(X_train, "TRAIN embeddings (2001-2023)")
stats(X_test,  "TEST  embeddings (2024-2026)")

# ── Cross-corpus similarity ────────────────────────────────────────────────────
print(f"\n{'─'*55}")
print(f"  CROSS-CORPUS COSINE SIMILARITY")
print(f"{'─'*55}")
S = cosine_sim_matrix(X_train, X_test)
print(f"  Shape: {S.shape}  (train x test)")
print(f"  Mean  : {S.mean():.4f}")
print(f"  Std   : {S.std():.4f}")
print(f"  Min   : {S.min():.4f}")
print(f"  Max   : {S.max():.4f}")
print(f"  >0.90 : {(S > 0.90).sum()} pairs")
print(f"  >0.80 : {(S > 0.80).sum()} pairs")
print(f"  >0.70 : {(S > 0.70).sum()} pairs")
print(f"  >0.50 : {(S > 0.50).sum()} pairs")
print(f"  >0.30 : {(S > 0.30).sum()} pairs")

# ── Within-corpus similarity (should be higher than cross) ────────────────────
print(f"\n{'─'*55}")
print(f"  WITHIN-CORPUS COSINE SIMILARITY (sanity check)")
print(f"{'─'*55}")
S_tt = cosine_sim_matrix(X_train, X_train)
triu_tt = S_tt[np.triu_indices(len(X_train), k=1)]
print(f"  Train-Train: mean={triu_tt.mean():.4f}  max={triu_tt.max():.4f}")

S_ee = cosine_sim_matrix(X_test, X_test)
triu_ee = S_ee[np.triu_indices(len(X_test), k=1)]
print(f"  Test-Test  : mean={triu_ee.mean():.4f}  max={triu_ee.max():.4f}")

# ── Top cross-matches ──────────────────────────────────────────────────────────
print(f"\n{'─'*55}")
print(f"  TOP 5 CROSS-CORPUS MATCHES")
print(f"{'─'*55}")
flat_idx = np.argsort(S.ravel())[::-1][:5]
for idx in flat_idx:
    i, j = divmod(idx, S.shape[1])
    print(f"  sim={S[i,j]:.4f}")
    print(f"    TRAIN: {train_texts[i]}")
    print(f"    TEST : {test_texts[j]}")
    print()

# ── Diagnosis ─────────────────────────────────────────────────────────────────
print(f"\n{'='*55}")
print(f"  DIAGNOSIS")
print(f"{'='*55}")

mean_cross = S.mean()
mean_within_train = triu_tt.mean()
mean_within_test  = triu_ee.mean()

if S.max() < 0.70:
    print(f"  ❌ CRITICAL: Max cross-corpus similarity = {S.max():.4f}")
    print(f"     Embeddings are likely from DIFFERENT BERT models.")
    print(f"     Train and test embeddings are NOT comparable.")
    print(f"     → Recompute one set using the other's model.")
elif abs(X_train.mean() - X_test.mean()) > 0.05:
    print(f"  ⚠  WARNING: Mean shift between corpora.")
    print(f"     Train mean={X_train.mean():.4f}  Test mean={X_test.mean():.4f}")
    print(f"     Possible different preprocessing or normalisation.")
elif mean_cross < 0.30:
    print(f"  ⚠  WARNING: Low cross-corpus similarity ({mean_cross:.4f}).")
    print(f"     Could be different BERT models or domain shift.")
elif mean_within_train > mean_cross * 1.5:
    print(f"  ⚠  Within-train similarity ({mean_within_train:.4f}) much higher")
    print(f"     than cross-corpus ({mean_cross:.4f}).")
    print(f"     Suggests embeddings may be from same model but different")
    print(f"     text preprocessing (cleaning, truncation, tokenisation).")
else:
    print(f"  ✓  Embeddings appear COMPATIBLE.")
    print(f"     Cross-corpus mean={mean_cross:.4f}")
    print(f"     Within-train mean={mean_within_train:.4f}")
    print(f"     Low max similarity is expected for oil news corpus")
    print(f"     (all documents are semantically close — dense embedding space).")

print(f"\n  Max possible similarity: {S.max():.4f}")
print(f"  This {'IS' if S.max() > 0.85 else 'IS NOT'} consistent with")
print(f"  same-BERT-model embeddings on similar text.")
print(f"{'='*55}\n")