"""
redflag_report_layer.py
=======================
Report generation router for Brahmanda v5.
Mounted by redflag_api.py as: app.include_router(report_router)

Endpoints added:
  POST /report   — generate analyst report (template or Claude LLM)
"""

import os, json, uuid, logging
from pathlib import Path
from fastapi import APIRouter, HTTPException

log = logging.getLogger("brahmanda.report")
report_router = APIRouter()

BASE = Path(os.environ.get("BASE_PATH", "."))


def _kde_context(event_id: str) -> dict:
    """Load KDE stats for an event from the results CSV."""
    try:
        import pandas as pd
        paths = [
            BASE / "kde_output_v3" / "kde_v3_results_h15.csv",
            Path("kde_output_v3") / "kde_v3_results_h15.csv",
        ]
        f = next((p for p in paths if p.exists()), None)
        if f is None:
            return {}
        df = pd.read_csv(f)
        row = df[df["event_id"] == event_id]
        if row.empty:
            return {}
        r = row.iloc[0]
        return {
            "event_id":    event_id,
            "red_flag":    int(r.get("red_flag", 0)),
            "signal":      str(r.get("signal", "")),
            "kde_p5":      float(r.get("kde_p5", -8)),
            "kde_median":  float(r.get("kde_median", 0)),
            "kde_p95":     float(r.get("kde_p95", 8)),
            "kde_std":     float(r.get("kde_std", 5)),
            "is_bimodal":  bool(r.get("kde_is_bimodal", 0)),
            "tail_weight": float(r.get("kde_tail_weight", 0.15)),
            "p_down10":    float(r.get("kde_p_down10", 0.05)),
            "garch_sigma": float(r.get("garch_sigma", 8)),
            "FEI":         float(r.get("FEI", 1.0)),
            "covers_90":   bool(r.get("covers_90", 1)),
            "realised_r":  float(r.get("realised_r", 0)) if "realised_r" in r else None,
        }
    except Exception as e:
        log.warning(f"KDE context load failed: {e}")
        return {}


def _template_report(ctx: dict, event_id: str) -> str:
    p5    = ctx.get("kde_p5", -8)
    med   = ctx.get("kde_median", 0)
    p95   = ctx.get("kde_p95", 8)
    bw    = p95 - p5
    bimod = ctx.get("is_bimodal", False)
    tw    = ctx.get("tail_weight", 0.15)
    pd10  = ctx.get("p_down10", 0.05)
    fei   = ctx.get("FEI", 1.0)
    rf    = ctx.get("red_flag", 0)
    sig   = ctx.get("signal", "NEUTRAL")
    garch = ctx.get("garch_sigma", 8)
    garch_bw = garch * 3.29  # P5-P95 for Gaussian

    risk_label = "⚠️ RED FLAG" if rf else "✅ NORMAL"
    sig_label  = {"LONG": "🟢 BULLISH", "SHORT": "🔴 BEARISH",
                  "NEUTRAL": "⚪ NEUTRAL"}.get(sig, sig)

    return f"""## Brahmanda Event Risk Report
**Event ID:** `{event_id}`
**Risk Status:** {risk_label} · **Signal:** {sig_label}

---

### KDE Posterior Summary
The selective prior framework produces a **{'bimodal' if bimod else 'unimodal'}** posterior:

| Metric | Value |
|--------|-------|
| P5 Downside | {p5:+.1f}% |
| Median Forecast | {med:+.1f}% |
| P95 Upside | {p95:+.1f}% |
| Band Width | {bw:.1f}% |
| Tail Weight | {tw*100:.0f}% |
| P(crash > 10%) | {pd10*100:.1f}% |

### Efficiency vs GARCH
The KDE framework produces a **{bw:.1f}%** prediction interval versus **{garch_bw:.1f}%** for GARCH(1,1) — a **{(garch_bw/bw-1)*100:.0f}% narrower band** (FEI = {fei:.3f}).

### Risk Assessment
{'⚠️ **Elevated tail risk.** The posterior assigns significant probability mass to extreme downside outcomes. Consider reducing exposure.' if rf or pd10 > 0.20 else '✅ **Within normal parameters.** No tail veto triggered. Standard risk management applies.'}

{'### Bimodal Scenario Structure' if bimod else ''}
{'The posterior exhibits two distinct modes, corresponding to a moderate-impact scenario and a tail-event scenario. The tail component carries **' + f"{tw*100:.0f}%" + '** of total probability mass.' if bimod else ''}

### Trading Implication
- **Signal:** {sig}
- **Action:** {"Reduce long exposure / hedge downside" if sig == "SHORT" or (rf and pd10 > 0.2) else "Increase exposure / add long" if sig == "LONG" else "Hold / monitor — no directional edge"}

---
*Generated by Brahmanda v5 — template engine.*
*Set `ANTHROPIC_API_KEY` for Claude-powered analyst reports.*"""


@report_router.post("/report")
def generate_report(payload: dict):
    """
    Generate an analyst report for an event.
    Payload: { event_id, use_llm, analysis }
    Returns: { report_id, event_id, engine, markdown }
    """
    event_id = payload.get("event_id", "")
    use_llm  = payload.get("use_llm", False)
    analysis = payload.get("analysis") or {}

    # Load real KDE context if event_id provided
    if event_id:
        ctx = _kde_context(event_id)
        if ctx:
            analysis = {**analysis, **ctx}
    else:
        ctx = analysis

    engine   = "template"
    markdown = ""

    # Try Claude LLM
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if use_llm and api_key:
        try:
            import anthropic
            client = anthropic.Anthropic(api_key=api_key)
            prompt = f"""You are a senior crude oil market analyst at an energy trading desk.
Write a concise analyst report (350-450 words) for this event analysis.
Use markdown with clear headers. Be specific, factual, and actionable.

Event Analysis Data:
{json.dumps(analysis, indent=2, default=str)}

Structure your report as:
1. Risk Assessment (2-3 sentences)
2. KDE Posterior Interpretation (what the distribution tells us)
3. Scenario Analysis (if bimodal, describe both scenarios)
4. Trading Implication (long/short/flat and why)
5. Key Risks to Watch

Be direct. A trader will act on this."""

            msg = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=700,
                messages=[{"role": "user", "content": prompt}]
            )
            markdown = msg.content[0].text
            engine   = "llm"
            log.info(f"[report] LLM report generated for {event_id}")
        except Exception as e:
            log.warning(f"[report] LLM failed, falling back to template: {e}")

    if not markdown:
        markdown = _template_report(ctx if ctx else analysis, event_id)
        engine   = "template"

    return {
        "report_id": str(uuid.uuid4())[:8],
        "event_id":  event_id,
        "engine":    engine,
        "markdown":  markdown,
    }
